#!/bin/bash

if [ -z "$PYFILE" ]; then
	echo "Error: PYFILE environment variable not set."
	exit 1
fi

OUTPUT_FILE="${PYFILE}c"
echo "Compiling $PYFILE ..."
python3 -m py_compile "$PYFILE" && mv "__pycache__/$PYFILE.cpython-*.pyc" "$OUTPUT_FILE" && rmdir "__pycache__"

ls -l "$OUTPUT_FILE"

